services:
  api:
    image: ${CONTAINER_IMAGE_NAME}:${CONTAINER_IMAGE_VERSION}
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - ${API_LISTEN_PORT:-8085}:${CONTAINER_LISTEN_PORT:-8085}
